import api from '../api';

/**
 * Service for interacting with the ASP.NET Core Accounts API (/api/v1/accounts).
 */
export const accountService = {
  /**
   * Retrieves bank accounts owned by the authenticated customer.
   * @returns {Promise<Array>} List of AccountResponse objects
   */
  async getAccounts() {
    const response = await api.get('/accounts');
    return response.data;
  },

  /**
   * Opens a new Savings or Checking bank account for the authenticated user.
   * Account number and ID are automatically generated by the backend.
   * @param {number} accountType - 1 for Savings, 2 for Checking
   * @returns {Promise<Object>} Created account payload
   */
  async createAccount(accountType) {
    const response = await api.post('/accounts', {
      accountType: Number(accountType),
    });
    return response.data;
  },

  /**
   * Retrieves account details by ID.
   * @param {string} id - Account GUID
   * @returns {Promise<Object>} AccountResponse
   */
  async getAccountById(id) {
    const response = await api.get(`/accounts/${id}`);
    return response.data;
  },

  /**
   * Queries balance and active status of a specific account.
   * @param {string} id - Account GUID
   * @returns {Promise<Object>} AccountBalanceResponse
   */
  async getAccountBalance(id) {
    const response = await api.get(`/accounts/${id}/balance`);
    return response.data;
  },

  /**
   * Soft-deletes / deactivates an account.
   * @param {string} id - Account GUID
   * @returns {Promise<Object>} Response message
   */
  async deactivateAccount(id) {
    const response = await api.delete(`/accounts/${id}`);
    return response.data;
  },
};

export default accountService;
