namespace BankAccountManagementSystem.API.Models
{
    /// <summary>
    /// Represents a bank account owned by an ApplicationUser.
    ///
    /// Key architectural decisions:
    /// 1. Decimal Balance: Money calculations must always use 128-bit decimal to avoid IEEE-754 floating point inaccuracies.
    /// 2. Unique AccountNumber: Auto-generated by backend, indexed, and unique across the bank.
    /// 3. Soft Delete (IsActive): Financial records cannot be purged. Closing an account marks IsActive = false.
    /// 4. Single Table Strategy: Both Savings and Checking accounts share the same core structural schema.
    ///    Their differences lie in transaction business rules (which are handled in service/transaction logic).
    /// 5. RowVersion (Concurrency Token): SQL Server-managed byte[] stamp used for optimistic concurrency control.
    ///    EF Core appends "WHERE RowVersion = @original" to every UPDATE on this row.
    ///    If two requests read the same Account row and both attempt a balance update concurrently,
    ///    the second UPDATE hits 0 rows → EF throws DbUpdateConcurrencyException → ExceptionMiddleware
    ///    returns 409 Conflict. This prevents double-spending without requiring explicit row locks.
    /// </summary>
    public class Account
    {
        /// <summary>
        /// Internal primary key (GUID) for database indexing and secure external routing.
        /// </summary>
        public Guid AccountId { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Customer-facing unique bank account number (e.g., 10-digit formatted account number).
        /// Generated by the backend.
        /// </summary>
        public string AccountNumber { get; set; } = string.Empty;

        /// <summary>
        /// Foreign key referencing the owning ApplicationUser.
        /// </summary>
        public string UserId { get; set; } = string.Empty;

        /// <summary>
        /// Navigation property to the owning ApplicationUser.
        /// </summary>
        public ApplicationUser? User { get; set; }

        /// <summary>
        /// Specifies whether this account is Savings or Checking.
        /// </summary>
        public AccountType AccountType { get; set; }

        /// <summary>
        /// Current account balance in base currency.
        /// Stored as decimal(18, 2) in SQL Server.
        /// Initialized strictly to 0.00m upon creation.
        /// </summary>
        public decimal Balance { get; set; } = 0.00m;

        /// <summary>
        /// Soft-delete status indicator.
        /// Deactivating an account sets this to false without deleting historical data.
        /// </summary>
        public bool IsActive { get; set; } = true;

        /// <summary>
        /// UTC timestamp of account creation.
        /// </summary>
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// UTC timestamp of last update (e.g. status change or transaction).
        /// </summary>
        public DateTime? UpdatedAt { get; set; }

        /// <summary>
        /// SQL Server rowversion column used as an EF Core concurrency token.
        /// Automatically managed by SQL Server — incremented on every UPDATE to this row.
        /// Never set or read by application code directly; EF Core handles it internally.
        /// Prevents two concurrent requests from both successfully modifying the same balance.
        /// </summary>
        public byte[]? RowVersion { get; set; }

        /// <summary>
        /// All transactions recorded against this account (1:N relationship).
        /// Each Deposit, Withdrawal, or Transfer leg is a separate Transaction row.
        /// Navigation property — not loaded by default (requires .Include() or explicit load).
        /// </summary>
        public ICollection<Transaction> Transactions { get; set; } = new List<Transaction>();
    }
}
