namespace BankAccountManagementSystem.API.Models
{
    /// <summary>
    /// Represents a financial transaction recorded against a bank account.
    ///
    /// Design decisions:
    ///
    /// 1. LEDGER-ENTRY MODEL (signed Amount):
    ///    Amount is always POSITIVE. The TransactionType determines the direction:
    ///      - Deposit   → balance increases by Amount.
    ///      - Withdrawal → balance decreases by Amount.
    ///      - Transfer  → two records created (one debit, one credit); Amount is
    ///                    always the absolute transferred value on both records.
    ///    This keeps the model simple and avoids confusion with negative amounts.
    ///    The service layer applies the correct arithmetic.
    ///
    /// 2. TWO RECORDS FOR TRANSFER:
    ///    A Cheque Transfer (Account A → Account B) creates exactly two Transaction rows:
    ///      Row 1: AccountId=A, Type=Transfer, Mode=Cheque, RelatedAccountId=B
    ///             (A is debited: balance decreases)
    ///      Row 2: AccountId=B, Type=Transfer, Mode=Cheque, RelatedAccountId=A
    ///             (B is credited: balance increases)
    ///    Each account has its own full ledger history. RelatedAccountId links both sides.
    ///
    /// 3. REFERENCE NUMBER:
    ///    Server-generated, not client-supplied. Format: TXN-YYYYMMDD-XXXXXXXX
    ///    Transfer reference: TXN-YYYYMMDD-XXXXXXXX-SRC / ...-DST to distinguish sides.
    ///
    /// 4. CONCURRENCY:
    ///    Account.RowVersion is a SQL Server rowversion token.
    ///    EF Core includes it in the WHERE clause on every UPDATE.
    ///    If two threads read the same Account and both attempt to save, the second
    ///    UPDATE hits 0 rows and EF throws DbUpdateConcurrencyException.
    ///    ExceptionMiddleware maps this to 409 Conflict.
    ///
    /// 5. SOFT DELETE SAFETY:
    ///    Transactions are NEVER cascade-deleted when an account is deactivated.
    ///    Accounts use soft delete (IsActive = false). The Account row is never
    ///    physically removed, so the FK in Transaction always points to a valid row.
    ///    DeleteBehavior.Restrict is configured in ApplicationDbContext.
    /// </summary>
    public class Transaction
    {
        /// <summary>
        /// Internal GUID primary key for secure, non-sequential external references.
        /// </summary>
        public Guid TransactionId { get; set; } = Guid.NewGuid();

        /// <summary>
        /// Foreign key: which account this ledger entry belongs to.
        /// For a Transfer, both the source and destination accounts have their own
        /// Transaction row with their respective AccountId.
        /// </summary>
        public Guid AccountId { get; set; }

        /// <summary>
        /// Navigation property to the owning Account.
        /// </summary>
        public Account? Account { get; set; }

        /// <summary>
        /// The direction of this ledger entry: Deposit, Withdrawal, or Transfer.
        /// </summary>
        public TransactionType TransactionType { get; set; }

        /// <summary>
        /// The payment instrument: Cash (single-account) or Cheque (Transfer between accounts).
        /// </summary>
        public TransactionMode TransactionMode { get; set; }

        /// <summary>
        /// The absolute monetary amount involved. Always positive.
        /// The service layer adds (Deposit/incoming Transfer) or subtracts (Withdrawal/outgoing Transfer)
        /// this value from the account balance.
        /// Stored as decimal(18,2). Never float or double.
        /// </summary>
        public decimal Amount { get; set; }

        /// <summary>
        /// UTC timestamp recorded by the server at the moment of transaction creation.
        /// Not accepted from the client.
        /// </summary>
        public DateTime TransactionDate { get; set; } = DateTime.UtcNow;

        /// <summary>
        /// Optional human-readable note supplied by the caller (e.g. "Salary deposit").
        /// </summary>
        public string? Description { get; set; }

        /// <summary>
        /// Unique transaction reference number generated by the server.
        /// Format: TXN-YYYYMMDD-XXXXXXXX
        /// Never supplied by the client.
        /// </summary>
        public string ReferenceNumber { get; set; } = string.Empty;

        /// <summary>
        /// For Transfer transactions: the other account involved in the transfer.
        ///   On the SOURCE row:      RelatedAccountId = destination account
        ///   On the DESTINATION row: RelatedAccountId = source account
        /// Null for Deposit and Withdrawal (single-account operations).
        /// </summary>
        public Guid? RelatedAccountId { get; set; }

        /// <summary>
        /// Navigation property to the related (other side) account for Transfers.
        /// </summary>
        public Account? RelatedAccount { get; set; }

        /// <summary>
        /// Transaction outcome. Always Completed for synchronous operations.
        /// Failed is reserved for future async / gateway integration.
        /// </summary>
        public TransactionStatus Status { get; set; } = TransactionStatus.Completed;
    }
}
