import { useState } from 'react';
import { Link } from 'react-router-dom';
import {
  CreditCard, ArrowLeft, CheckCircle2, Loader2,
  Check, X, AlertCircle, PlusCircle
} from 'lucide-react';
import accountService from '../services/accountService';
import styles from './AddAccountPage.module.css';

export default function AddAccountPage() {
  // 1 = Savings, 2 = Checking
  const [accountType, setAccountType] = useState(1);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const [createdAccount, setCreatedAccount] = useState(null);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError('');
    setLoading(true);

    try {
      // Calls POST /api/v1/accounts with { accountType: 1 | 2 }
      // Server generates Account Number and initializes balance to 0.00
      const res = await accountService.createAccount(accountType);
      setCreatedAccount(res.account || res);
    } catch (err) {
      console.error('Account creation error:', err);
      setError(err.response?.data?.message || 'Failed to open account. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className={styles.pageContent}>
      <Link to="/accounts" className={styles.backLink}>
        <ArrowLeft size={16} /> Back to Accounts
      </Link>

      {createdAccount ? (
        /* ── Success Screen ────────────────────────────────────────── */
        <div className={styles.successCard}>
          <div className={styles.successIcon}><CheckCircle2 size={40} /></div>
          <h2 className={styles.successTitle}>Bank Account Created!</h2>
          <p className={styles.successBody}>
            Your new bank account has been opened successfully. Below are your account details generated by the backend:
          </p>

          <div className={styles.detailsBox}>
            <div className={styles.detailRow}>
              <span className={styles.detailLabel}>Account Number</span>
              <span className={styles.detailValue}>{createdAccount.accountNumber}</span>
            </div>

            <div className={styles.detailRow}>
              <span className={styles.detailLabel}>Account Type</span>
              <span className={styles.detailValue} style={{ textTransform: 'capitalize' }}>
                {typeof createdAccount.accountType === 'string'
                  ? createdAccount.accountType
                  : createdAccount.accountType === 1 ? 'Savings' : 'Checking'}
              </span>
            </div>

            <div className={styles.detailRow}>
              <span className={styles.detailLabel}>Current Balance</span>
              <span className={styles.detailValue}>
                ${(createdAccount.balance ?? 0).toFixed(2)}
              </span>
            </div>
          </div>

          <div className={styles.actionGroup}>
            <Link to="/accounts" className={styles.viewBtn}>
              View All Accounts
            </Link>
            <button
              onClick={() => setCreatedAccount(null)}
              className={styles.anotherBtn}
            >
              <PlusCircle size={16} /> Open Another Account
            </button>
          </div>
        </div>
      ) : (
        /* ── Account Creation Form ──────────────────────────────────── */
        <>
          <div className={styles.pageHeader}>
            <h1 className={styles.pageTitle}>Open a Bank Account</h1>
            <p className={styles.pageSubtitle}>
              Select an account type. Your account number will be generated automatically.
            </p>
          </div>

          {error && (
            <div className={styles.errorBanner} role="alert">
              <AlertCircle size={16} />
              <span>{error}</span>
            </div>
          )}

          <form onSubmit={handleSubmit} className={styles.formCard}>
            <div className={styles.typeGrid}>

              {/* Savings Option */}
              <div
                onClick={() => setAccountType(1)}
                className={`${styles.typeOption} ${accountType === 1 ? styles.typeOptionSelected : ''}`}
                role="radio"
                aria-checked={accountType === 1}
              >
                <div className={styles.optionHeader}>
                  <div className={styles.optionIcon}><CreditCard size={22} /></div>
                  {accountType === 1 && (
                    <div className={styles.optionCheck}><Check size={13} /></div>
                  )}
                </div>
                <div>
                  <h3 className={styles.optionTitle}>Savings Account</h3>
                  <p className={styles.optionDesc}>
                    Personal savings account for building balance securely.
                  </p>
                </div>
                <div className={styles.ruleList}>
                  <span className={`${styles.ruleTag} ${styles.ruleAllow}`}>
                    <Check size={12} /> Cash transactions allowed
                  </span>
                  <span className={`${styles.ruleTag} ${styles.ruleDeny}`}>
                    <X size={12} /> Cheque transactions NOT allowed
                  </span>
                </div>
              </div>

              {/* Checking Option */}
              <div
                onClick={() => setAccountType(2)}
                className={`${styles.typeOption} ${accountType === 2 ? styles.typeOptionSelected : ''}`}
                role="radio"
                aria-checked={accountType === 2}
              >
                <div className={styles.optionHeader}>
                  <div className={styles.optionIcon} style={{ background: 'rgba(59,130,246,0.15)', color: '#3b82f6' }}>
                    <CreditCard size={22} />
                  </div>
                  {accountType === 2 && (
                    <div className={styles.optionCheck}><Check size={13} /></div>
                  )}
                </div>
                <div>
                  <h3 className={styles.optionTitle}>Checking Account</h3>
                  <p className={styles.optionDesc}>
                    Everyday transaction account supporting cash & cheque operations.
                  </p>
                </div>
                <div className={styles.ruleList}>
                  <span className={`${styles.ruleTag} ${styles.ruleAllow}`}>
                    <Check size={12} /> Cash transactions allowed
                  </span>
                  <span className={`${styles.ruleTag} ${styles.ruleAllow}`}>
                    <Check size={12} /> Cheque transactions allowed
                  </span>
                </div>
              </div>

            </div>

            <button type="submit" className={styles.submitBtn} disabled={loading}>
              {loading ? (
                <><Loader2 size={18} className={styles.spinner} /> Opening Account…</>
              ) : (
                <><CreditCard size={18} /> Open Account</>
              )}
            </button>
          </form>
        </>
      )}
    </div>
  );
}
