import { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import {
  User, Mail, Lock, Eye, EyeOff, Phone, BadgeCheck,
  AlertCircle, CheckCircle2, Loader2, Building2, ArrowLeft,
  MapPin, CreditCard,
} from 'lucide-react';
import api from '../api';
import styles from './RegisterPage.module.css';

// ─── Password rules (must mirror backend Identity config) ────────────────────
const PASSWORD_RULES = [
  { test: (p) => p.length >= 8,          label: 'At least 8 characters' },
  { test: (p) => /[A-Z]/.test(p),        label: 'One uppercase letter' },
  { test: (p) => /[a-z]/.test(p),        label: 'One lowercase letter' },
  { test: (p) => /[0-9]/.test(p),        label: 'One number' },
  { test: (p) => /[^A-Za-z0-9]/.test(p), label: 'One special character (!@#$…)' },
];

// ─── Minimal field-level validators ──────────────────────────────────────────
function validate(fields) {
  const errors = {};

  if (!fields.firstName.trim())
    errors.firstName = 'First name is required.';

  if (!fields.lastName.trim())
    errors.lastName = 'Last name is required.';

  if (!fields.email.trim()) {
    errors.email = 'Email is required.';
  } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(fields.email.trim())) {
    errors.email = 'Enter a valid email address.';
  }

  if (fields.phone && fields.phone.trim() && !/^\+?[\d\s\-().]{7,20}$/.test(fields.phone.trim())) {
    errors.phone = 'Enter a valid phone number.';
  }

  if (!fields.password) {
    errors.password = 'Password is required.';
  } else {
    const failing = PASSWORD_RULES.filter((r) => !r.test(fields.password));
    if (failing.length > 0) errors.password = 'Password does not meet all requirements.';
  }

  if (!fields.confirmPassword) {
    errors.confirmPassword = 'Please confirm your password.';
  } else if (fields.password !== fields.confirmPassword) {
    errors.confirmPassword = 'Passwords do not match.';
  }

  return errors;
}

// ─── Reusable field component ─────────────────────────────────────────────────
function Field({ id, label, icon: Icon, error, children }) {
  return (
    <div className={styles.field}>
      <label htmlFor={id} className={styles.label}>{label}</label>
      <div className={styles.inputWrap}>
        <Icon size={15} className={styles.inputIcon} />
        {children}
      </div>
      {error && (
        <p className={styles.fieldError} role="alert">
          <AlertCircle size={12} /> {error}
        </p>
      )}
    </div>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────
export default function RegisterPage() {
  const navigate = useNavigate();

  const [fields, setFields] = useState({
    firstName: '',
    lastName: '',
    email: '',
    phone: '',
    address: '',
    password: '',
    confirmPassword: '',
  });

  const [errors,        setErrors]        = useState({});
  const [apiError,      setApiError]      = useState('');
  const [generatedData, setGeneratedData] = useState(null);
  const [loading,       setLoading]       = useState(false);
  const [showPass,      setShowPass]      = useState(false);
  const [showConf,      setShowConf]      = useState(false);
  const [touched,       setTouched]       = useState({});

  // Live-update a single field
  const set = (key) => (e) => {
    setFields((prev) => ({ ...prev, [key]: e.target.value }));
    if (touched[key]) {
      const updated = { ...fields, [key]: e.target.value };
      const errs = validate(updated);
      setErrors((prev) => ({ ...prev, [key]: errs[key] }));
    }
  };

  const touch = (key) => () => {
    setTouched((prev) => ({ ...prev, [key]: true }));
    const errs = validate(fields);
    setErrors((prev) => ({ ...prev, [key]: errs[key] }));
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setApiError('');

    // Mark all required fields as touched
    setTouched({ firstName: true, lastName: true, email: true, phone: true, address: true, password: true, confirmPassword: true });

    const errs = validate(fields);
    setErrors(errs);
    if (Object.keys(errs).length > 0) return;

    setLoading(true);
    try {
      // POST /api/v1/auth/register
      // Customer ID and Bank Account Number are auto-generated by the backend
      const res = await api.post('/auth/register', {
        firstName: fields.firstName.trim(),
        lastName:  fields.lastName.trim(),
        email:     fields.email.trim(),
        phone:     fields.phone.trim() || undefined,
        address:   fields.address.trim() || undefined,
        password:  fields.password,
      });

      setGeneratedData({
        customerId: res.data?.customerId || null,
      });
    } catch (err) {
      const status  = err.response?.status;
      const message = err.response?.data?.message;

      if (status === 409) {
        setApiError(message || 'An account with this email address already exists.');
      } else if (status === 400) {
        setApiError(message || 'Invalid registration details. Please check the fields.');
      } else if (status === 500) {
        setApiError(message || 'Internal server error (500). Please contact support.');
      } else if (!err.response) {
        setApiError('Unable to connect to the backend server. Please verify backend is running on https://localhost:7225.');
      } else {
        setApiError(message || `Registration failed (HTTP ${status}).`);
      }
    } finally {
      setLoading(false);
    }
  };

  // ── Success screen displaying backend-generated credentials ──────────────
  if (generatedData) {
    return (
      <div className={styles.root}>
        <div className={styles.grid} aria-hidden="true" />
        <div className={styles.orb1} aria-hidden="true" />
        <div className={styles.orb2} aria-hidden="true" />
        <main className={`${styles.card} ${styles.successCard}`}>
          <div className={styles.successIcon}><CheckCircle2 size={40} /></div>
          <h2 className={styles.successTitle}>Registration Successful!</h2>
          <p className={styles.successBody}>
            Your customer profile has been created successfully. You can now sign in and open your bank accounts.
          </p>

          {generatedData.customerId && (
            <div className={styles.generatedBox}>
              <div className={styles.generatedItem}>
                <span className={styles.generatedLabel}>
                  <BadgeCheck size={14} /> Customer ID
                </span>
                <span className={styles.generatedValue}>{generatedData.customerId}</span>
              </div>
            </div>
          )}

          <Link to="/login" className={styles.proceedBtn}>
            Proceed to Sign In <ArrowLeft size={16} style={{ transform: 'rotate(180deg)' }} />
          </Link>
        </main>
      </div>
    );
  }

  const passStrength = PASSWORD_RULES.filter((r) => r.test(fields.password)).length;

  // ── Form ───────────────────────────────────────────────────────────────────
  return (
    <div className={styles.root}>
      <div className={styles.grid} aria-hidden="true" />
      <div className={styles.orb1} aria-hidden="true" />
      <div className={styles.orb2} aria-hidden="true" />

      <main className={styles.card}>

        {/* Logo */}
        <div className={styles.logoWrap}>
          <div className={styles.logoIcon}><Building2 size={26} /></div>
          <div>
            <h1 className={styles.logoName}>NexaBank</h1>
            <p className={styles.logoTagline}>Banking Management System</p>
          </div>
        </div>

        <div className={styles.divider} />

        {/* Heading */}
        <div className={styles.heading}>
          <h2 className={styles.headingTitle}>Open a Bank Account</h2>
          <p className={styles.headingSubtitle}>Customer ID & Account Number will be generated automatically</p>
        </div>

        {/* API error */}
        {apiError && (
          <div className={styles.errorBanner} role="alert">
            <AlertCircle size={15} />
            <span>{apiError}</span>
          </div>
        )}

        <form onSubmit={handleSubmit} noValidate className={styles.form}>

          {/* Name row */}
          <div className={styles.row}>
            <Field id="firstName" label="First Name" icon={User} error={errors.firstName}>
              <input
                id="firstName"
                type="text"
                autoComplete="given-name"
                placeholder="Jane"
                value={fields.firstName}
                onChange={set('firstName')}
                onBlur={touch('firstName')}
                className={`${styles.input} ${errors.firstName ? styles.inputError : ''}`}
                disabled={loading}
              />
            </Field>
            <Field id="lastName" label="Last Name" icon={User} error={errors.lastName}>
              <input
                id="lastName"
                type="text"
                autoComplete="family-name"
                placeholder="Doe"
                value={fields.lastName}
                onChange={set('lastName')}
                onBlur={touch('lastName')}
                className={`${styles.input} ${errors.lastName ? styles.inputError : ''}`}
                disabled={loading}
              />
            </Field>
          </div>

          {/* Email */}
          <Field id="email" label="Email Address" icon={Mail} error={errors.email}>
            <input
              id="email"
              type="email"
              autoComplete="email"
              placeholder="jane.doe@email.com"
              value={fields.email}
              onChange={set('email')}
              onBlur={touch('email')}
              className={`${styles.input} ${errors.email ? styles.inputError : ''}`}
              disabled={loading}
            />
          </Field>

          {/* Phone (optional) */}
          <Field id="phone" label="Phone Number (optional)" icon={Phone} error={errors.phone}>
            <input
              id="phone"
              type="tel"
              autoComplete="tel"
              placeholder="+91 8698745896"
              value={fields.phone}
              onChange={set('phone')}
              onBlur={touch('phone')}
              className={`${styles.input} ${errors.phone ? styles.inputError : ''}`}
              disabled={loading}
            />
          </Field>

          {/* Address (optional) */}
          <Field id="address" label="Street Address (optional)" icon={MapPin} error={errors.address}>
            <input
              id="address"
              type="text"
              autoComplete="street-address"
              placeholder="123 Financial Way, Suite 400"
              value={fields.address}
              onChange={set('address')}
              onBlur={touch('address')}
              className={`${styles.input} ${errors.address ? styles.inputError : ''}`}
              disabled={loading}
            />
          </Field>

          {/* Password */}
          <div className={styles.field}>
            <label htmlFor="password" className={styles.label}>Password</label>
            <div className={styles.inputWrap}>
              <Lock size={15} className={styles.inputIcon} />
              <input
                id="password"
                type={showPass ? 'text' : 'password'}
                autoComplete="new-password"
                placeholder="Create a strong password"
                value={fields.password}
                onChange={set('password')}
                onBlur={touch('password')}
                className={`${styles.input} ${styles.inputPaddedRight} ${errors.password ? styles.inputError : ''}`}
                disabled={loading}
              />
              <button type="button" onClick={() => setShowPass((v) => !v)}
                className={styles.toggleBtn} tabIndex={-1}
                aria-label={showPass ? 'Hide password' : 'Show password'}>
                {showPass ? <EyeOff size={15} /> : <Eye size={15} />}
              </button>
            </div>

            {/* Strength bar */}
            {fields.password && (
              <div className={styles.strengthWrap}>
                <div className={styles.strengthBar}>
                  {PASSWORD_RULES.map((_, i) => (
                    <div
                      key={i}
                      className={`${styles.strengthSegment} ${i < passStrength ? styles[`str${passStrength}`] : ''}`}
                    />
                  ))}
                </div>
                <span className={styles.strengthLabel}>
                  {['', 'Very Weak', 'Weak', 'Fair', 'Strong', 'Very Strong'][passStrength]}
                </span>
              </div>
            )}

            {/* Rule checklist */}
            {(touched.password || fields.password) && (
              <ul className={styles.ruleList}>
                {PASSWORD_RULES.map((rule) => (
                  <li key={rule.label}
                    className={`${styles.rule} ${rule.test(fields.password) ? styles.rulePassed : ''}`}>
                    <CheckCircle2 size={11} />
                    {rule.label}
                  </li>
                ))}
              </ul>
            )}

            {errors.password && (
              <p className={styles.fieldError} role="alert">
                <AlertCircle size={12} /> {errors.password}
              </p>
            )}
          </div>

          {/* Confirm password */}
          <Field id="confirmPassword" label="Confirm Password" icon={Lock} error={errors.confirmPassword}>
            <input
              id="confirmPassword"
              type={showConf ? 'text' : 'password'}
              autoComplete="new-password"
              placeholder="Repeat your password"
              value={fields.confirmPassword}
              onChange={set('confirmPassword')}
              onBlur={touch('confirmPassword')}
              className={`${styles.input} ${styles.inputPaddedRight} ${errors.confirmPassword ? styles.inputError : ''}`}
              disabled={loading}
            />
            <button type="button" onClick={() => setShowConf((v) => !v)}
              className={styles.toggleBtn} tabIndex={-1}
              aria-label={showConf ? 'Hide' : 'Show'}>
              {showConf ? <EyeOff size={15} /> : <Eye size={15} />}
            </button>
          </Field>

          {/* Submit */}
          <button type="submit" className={styles.submitBtn} disabled={loading}>
            {loading ? (
              <><Loader2 size={17} className={styles.spinner} /> Registering Account…</>
            ) : (
              <><BadgeCheck size={17} /> Register Account</>
            )}
          </button>
        </form>

        {/* Already have account */}
        <p className={styles.loginLink}>
          Already have an account?{' '}
          <Link to="/login" className={styles.link}>
            <ArrowLeft size={13} /> Sign In
          </Link>
        </p>
      </main>
    </div>
  );
}
